# Generated by Django 6.0.6 on 2026-08-17 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobPortalApp', '0002_seekeermodel_seeker'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyjobmodel',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
